In [1]:
import pandas as pd
import numpy as np
import collections
from sklearn.feature_extraction import text

In [2]:
data = pd.read_csv('F:/sentiment_analysis_task/Evaluation-dataset.csv', header=None)
data.head()

0   \
0  Tires where delivered to the garage of my choi...   
1  Easy Tyre Selection Process, Competitive Prici...   
2         Very easy to use and good value for money.   
3              Really easy and convenient to arrange   
4  It was so easy to select tyre sizes and arrang...   

                         1                         2   \
0   garage service positive  ease of booking positive   
1   garage service positive  value for money positive   
2  value for money positive                       NaN   
3  ease of booking positive                       NaN   
4         location positive  value for money positive   

                         3    4    5    6    7    8    9    10   11   12   13  \
0                       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1                       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2                       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3                       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
4  ease of booking positive  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

    14  
0  NaN  
1  NaN  
2  NaN  
3  NaN  
4  NaN

In [3]:
sentiment_array = ['Sentiment_'+ str(i) for i in range(1,15)]

new_col = ['Sentence'] + sentiment_array

data.columns = new_col

data.columns

Index(['Sentence', 'Sentiment_1', 'Sentiment_2', 'Sentiment_3', 'Sentiment_4',
       'Sentiment_5', 'Sentiment_6', 'Sentiment_7', 'Sentiment_8',
       'Sentiment_9', 'Sentiment_10', 'Sentiment_11', 'Sentiment_12',
       'Sentiment_13', 'Sentiment_14'],
      dtype='object')

In [4]:
sent = {}

for i in data.columns:
    if i!='Sentence':
        z = data[i].dropna()
        for l in z:
            if l not in sent.keys():
                sent[l] = 1
            else:
                sent[l]+=1

In [7]:
dict1

{'value for money positive': 4780,
 'garage service positive': 2031,
 'ease of booking positive': 1187,
 'location positive': 1063,
 'length of fitting positive': 657,
 'delivery punctuality positive': 453,
 'tyre quality positive': 434,
 'garage service negative': 423,
 'change of date negative': 277,
 'wait time positive': 274,
 'delivery punctuality negative': 250,
 'advisoragent service positive': 233,
 'ease of booking negative': 227,
 'mobile fitter positive': 225,
 'advisor/agent service positive': 202,
 'value for money negative': 136,
 'wait time negative': 135,
 'damage negative': 127,
 'advisoragent service negative': 125,
 'booking confusion negative': 119,
 'discounts positive': 115,
 'length of fitting negative': 109,
 'extra charges positive': 85,
 'response time negative': 77,
 'late notice negative': 76,
 'incorrect tyres sent negative': 70,
 'advisor/agent service negative': 47,
 'extra charges negative': 46,
 'change of time negative': 42,
 'no stock negative': 42,
 

In [5]:
import operator
dict1 = dict( sorted(sent.items(), key=operator.itemgetter(1),reverse=True))

list_polar = []

for key, value in dict1.items():
        
    if value>30:
            
        list_polar.append(key)

list_polar

['value for money positive',
 'garage service positive',
 'ease of booking positive',
 'location positive',
 'length of fitting positive',
 'delivery punctuality positive',
 'tyre quality positive',
 'garage service negative',
 'change of date negative',
 'wait time positive',
 'delivery punctuality negative',
 'advisoragent service positive',
 'ease of booking negative',
 'mobile fitter positive',
 'advisor/agent service positive',
 'value for money negative',
 'wait time negative',
 'damage negative',
 'advisoragent service negative',
 'booking confusion negative',
 'discounts positive',
 'length of fitting negative',
 'extra charges positive',
 'response time negative',
 'late notice negative',
 'incorrect tyres sent negative',
 'advisor/agent service negative',
 'extra charges negative',
 'change of time negative',
 'no stock negative',
 'tyre quality negative',
 'response time positive',
 'facilities positive']

In [6]:
len(list_polar)

33

In [8]:
def replacePosNeg(word):
    if(word.find('positive')>0):
        word = word.replace(" positive",'')
    if(word.find('negative')>0):
        word = word.replace(" negative",'')
    return word

In [9]:
list_2 = []
for word in list_polar:
    list_2.append(replacePosNeg(word))
list_2 = pd.Series(list_2).unique()
list_2

array(['value for money', 'garage service', 'ease of booking', 'location',
       'length of fitting', 'delivery punctuality', 'tyre quality',
       'change of date', 'wait time', 'advisoragent service',
       'mobile fitter', 'advisor/agent service', 'damage',
       'booking confusion', 'discounts', 'extra charges', 'response time',
       'late notice', 'incorrect tyres sent', 'change of time',
       'no stock', 'facilities'], dtype=object)

In [10]:
def dataModification(data,Considerpolarity):
    
    data1 = data.iloc[:, 1:]
    if(Considerpolarity==True):
        data2 = pd.DataFrame(index= range(0, data1.shape[0]), columns=list_polar)
    else:
        data2 = pd.DataFrame(index= range(0, data1.shape[0]), columns=list_2)
    
    for i, row in data1.iterrows():
        
        l_subthemes = row.dropna().tolist()
        
        for t in l_subthemes:
            
            if(Considerpolarity==True):
                data2.loc[i][t] = 1
            else :
                data2.loc[i][replacePosNeg(t)] = -1
                

    data2 = data2.fillna(0)
    finalData = pd.DataFrame()
    finalData['Sentence'] = data['Sentence']
    for column in data2.columns:
        finalData[column] = data2[column]
    return finalData

In [11]:
finalData = dataModification(data,True)
finalData.head(20)

Sentence  \
0   Tires where delivered to the garage of my choi...   
1   Easy Tyre Selection Process, Competitive Prici...   
2          Very easy to use and good value for money.   
3               Really easy and convenient to arrange   
4   It was so easy to select tyre sizes and arrang...   
5   service was excellent. Only slight downside wa...   
6   User friendly Website. Competitive Prices. Goo...   
7                        Excellent prices and service   
8   It was very straightforward and the garage was...   
9                                Use of local garage.   
10                      Easy to use, also good price.   
11  Outstanding values for money and a friendly pr...   
12                        Great price and easy to use   
13  Good price and easy to use a garage I was fami...   
14  Booked slot then you couldn't provide it and h...   
15           Good price and some good fitting centres   
16  Competitively priced and easy to use fitting c...   
17  Very easy to use. I was kept up to date every ...   
18  A really easy website to navigate, competitive...   
19      A very good experience and a set time booking   

    value for money positive  garage service positive  \
0                          0                        1   
1                          1                        1   
2                          1                        0   
3                          0                        0   
4                          1                        0   
5                          0                        0   
6                          1                        1   
7                          1                        0   
8                          0                        1   
9                          0                        0   
10                         1                        0   
11                         1                        0   
12                         1                        0   
13                         1                        0   
14                         0                        0   
15                         1                        1   
16                         1                        1   
17                         1                        0   
18                         1                        0   
19                         0                        0   

    ease of booking positive  location positive  length of fitting positive  \
0                          1                  0                           0   
1                          0                  0                           0   
2                          0                  0                           0   
3                          1                  0                           0   
4                          1                  1                           0   
5                          1                  0                           1   
6                          0                  0                           0   
7                          0                  0                           0   
8                          0                  0                           0   
9                          0                  1                           0   
10                         0                  0                           0   
11                         0                  0                           0   
12                         0                  0                           0   
13                         0                  1                           0   
14                         0                  0                           0   
15                         0                  0                           0   
16                         0                  1                           0   
17                         0                  0                           0   
18                         0                  0                           0   
19                         1                  0                      

In [49]:
import nltk
def stem_with_porter(words):
    porter = nltk.PorterStemmer()
    new_words = [porter.stem(w) for w in words]
    return new_words    

porter = [stem_with_porter(x.split()) for x in sent_processed_3]

porter = [" ".join(i) for i in porter]

porter[:10]

['tire deliv garag choic garag notifi deliv day time arrang garag went fit hassel free experi',
 'easi tyre select process competit price excel fit servic',
 'easi use good valu money',
 'realli easi conveni arrang',
 'easi select tyre size arrang local fit price competit',
 'servic excel slight downsid know exact time garag although garag quick delay',
 'user friendli websit competit price good commun effici servic at euromast',
 'excel price servic',
 'straightforward garag great even known',
 'use local garag']

In [50]:
len(porter)

10132

In [51]:
voc_size=10132
from tensorflow.keras.preprocessing.text import one_hot
onehot_repr=[one_hot(words,voc_size)for words in porter] 
onehot_repr[:10]

[[3961,
  5028,
  9188,
  10042,
  9188,
  1931,
  5028,
  8473,
  6444,
  5231,
  9188,
  2270,
  3903,
  9229,
  6699,
  5179],
 [9723, 7781, 3978, 3896, 804, 9319, 1458, 3903, 7758],
 [9723, 7794, 9888, 4674, 465],
 [2214, 9723, 704, 5231],
 [9723, 3978, 7781, 1715, 5231, 7032, 3903, 9319, 804],
 [7758, 1458, 8201, 321, 740, 297, 6444, 9188, 8635, 9188, 2963, 3561],
 [5831, 628, 4016, 804, 9319, 9888, 7931, 2644, 7758, 5312, 639],
 [1458, 9319, 7758],
 [2301, 9188, 2991, 8161, 6559],
 [7794, 7032, 9188]]

In [53]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import SpatialDropout1D

In [57]:
sent_length=25
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 9229 6699 5179]
 [   0    0    0 ... 1458 3903 7758]
 [   0    0    0 ... 9888 4674  465]
 ...
 [   0    0 5810 ... 2963 3118 9374]
 [   0    0    0 ... 3903 9131 8308]
 [   0    0    0 ... 9095 6618 4878]]


In [60]:
data_pred = finalData.iloc[:,1:]
data_pred.head()

value for money positive  garage service positive  \
0                         0                        1   
1                         1                        1   
2                         1                        0   
3                         0                        0   
4                         1                        0   

   ease of booking positive  location positive  length of fitting positive  \
0                         1                  0                           0   
1                         0                  0                           0   
2                         0                  0                           0   
3                         1                  0                           0   
4                         1                  1                           0   

   delivery punctuality positive  tyre quality positive  \
0                              0                      0   
1                              0                      0   
2                              0                      0   
3                              0                      0   
4                              0                      0   

   garage service negative  change of date negative  wait time positive  ...  \
0                        0                        0                   0  ...   
1                        0                        0                   0  ...   
2                        0                        0                   0  ...   
3                        0                        0                   0  ...   
4                        0                        0                   0  ...   

   response time negative  late notice negative  \
0                       0                     0   
1                       0                     0   
2                       0                     0   
3                       0                     0   
4                       0                     0   

   incorrect tyres sent negative  advisor/agent service negative  \
0                              0                               0   
1                              0                               0   
2                              0                               0   
3                              0                               0   
4                              0                               0   

   extra charges negative  change of time negative  no stock negative  \
0                       0                        0                  0   
1                       0                        0                  0   
2                       0                        0                  0   
3                       0                        0                  0   
4                       0                        0                  0   

   tyre quality negative  response time positive  facilities positive  
0                      0                       0                    0  
1                      0                       0                    0  
2                      0                       0                    0  
3                      0                       0                    0  
4                      0                       0                    0  

[5 rows x 33 columns]

In [61]:
X = np.array(embedded_docs)
Y = np.array(data_pred)

In [62]:
EMBEDDING_DIM = 100 
model = Sequential()
model.add(Embedding(voc_size, EMBEDDING_DIM, input_length=sent_length))
model.add(LSTM(250, dropout=0.2,return_sequences=True))
model.add(LSTM(150, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(33, activation='sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 25, 100)           1013200   
_________________________________________________________________
lstm (LSTM)                  (None, 25, 250)           351000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 150)               240600    
_________________________________________________________________
dense (Dense)                (None, 33)                4983      
Total params: 1,609,783
Trainable params: 1,609,783
Non-trainable params: 0
_________________________________________________________________
None


In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [65]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5,batch_size=64)

Epoch 1/5
111/111 [==============================] - 36s 328ms/step - loss: 3.4883 - accuracy: 0.6750 - val_loss: 3.6287 - val_accuracy: 0.6737
Epoch 2/5
111/111 [==============================] - 37s 329ms/step - loss: 3.4886 - accuracy: 0.6750 - val_loss: 3.6192 - val_accuracy: 0.6737
Epoch 3/5
111/111 [==============================] - 37s 330ms/step - loss: 3.4889 - accuracy: 0.6750 - val_loss: 3.6155 - val_accuracy: 0.6737
Epoch 4/5
111/111 [==============================] - 37s 329ms/step - loss: 3.4597 - accuracy: 0.6732 - val_loss: 3.5334 - val_accuracy: 0.6737
Epoch 5/5
111/111 [==============================] - 36s 326ms/step - loss: 3.5790 - accuracy: 0.6747 - val_loss: 3.4427 - val_accuracy: 0.6737


In [66]:
y_pred=np.argmax(model.predict(X_test), axis=-1)
len(y_pred)

3040

In [72]:
Y_test=np.argmax(y_test, axis=1)
len(Y_test)

3040

In [73]:
from sklearn import metrics
print(metrics.classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      1.00      0.81      2048
           1       0.00      0.00      0.00       349
           2       0.00      0.00      0.00       129
           3       0.00      0.00      0.00        39
           4       0.00      0.00      0.00        35
           5       0.00      0.00      0.00        33
           6       0.00      0.00      0.00        23
           7       0.00      0.00      0.00        85
           8       0.00      0.00      0.00        72
           9       0.00      0.00      0.00        16
          10       0.00      0.00      0.00        32
          11       0.00      0.00      0.00        26
          12       0.00      0.00      0.00        26
          13       0.00      0.00      0.00        17
          14       0.00      0.00      0.00        19
          15       0.00      0.00      0.00        24
          16       0.00      0.00      0.00         6
          17       0.00    

C:\Users\AAA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
